export class Login {
  public email: string;
  public password: string;
}
export class Cadastro {
  public email: string;
  public password: string;
  public nome: string;
  public sobrenome: string;
}
export class Perfil {
  nome: string;
  email: string;
  sobrenome: string;
  fotoAvatar: string;
  nomeArtistico: string;
  nomePai: string;
  nomeMae: string;
  rg: string;
  cpf: string;
  categoriaCnh: string;
  nacionalidade: string;
  naturalidade: string;
  cep: string;
  endereco: string;
  numero: string;
  complemento: string;
  facebook: string;
  instagram: string;
  site: string;
  youTube: string;
  banco: string;
  agencia: string;
  conta: string;
  tipoDeConta: string;
  nomeFavorecido: string;
  trabalhaComFiguracao: string;
  drt: string;
  estado: string;
  cidade: string;
  bairro: string;
  sexo: string;
  dataDeNascimento: string;
  celular: string;
  telefone: string;
  altura: string;
  peso: string;
  manequim: string;
  quadril: string;
  busto: string;
  cintura: string;
  camisa: string;
  terno: string;
  calcado: string;
  corDosOlhos: string;
  pele: string;
  conhecimentosEmWindows: string;
  conhecimentosEmWord: string;
  conhecimentosEmExcel: string;
  linkParaVideoBook: string;
  localTatuagem: string;
  drtLocutor: string;
  drtDublador: string;
  outraLingua: string;
  curriculo: string;
  tipo: string;
  fisiologia: string;
  objetivos: string;
  cordoCabelo: string;
  tipoDeCabelo: string;
  escolaridade: string;
  ingles: string;
  espanhol: string;
  frances: string;
  temBarba: boolean;
  temBigode: boolean;
  temIrmaoGemeo: boolean;
  temPiercing: boolean;
  temCarro: boolean;
  temMoto: boolean;
  temTatuagem: boolean;
  locutor: boolean;
  dublador: boolean;
  cantor: boolean;
  conheceAlgumAnao: boolean;
  cacheMinimo: string;
  esportes: string;
  dancas: string;
  experienciaComoModelo: string;
  atividadesCircenses: string;
  trabalhosEmEventos: string;
  instrumentosMusicais: string;
  modelodePartesdoCorpo: string;
  artes: string;
}
